// redux에서 사용할 상태 타입

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

// user loading
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST"
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS"
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE"

// clear error
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST"
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS"
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE"

// register
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

// post write
export const POST_WRITE_REQUEST = "POST_WRITE_REQUEST"
export const POST_WRITE_SUCCESS = "POST_WRITE_SUCCESS"
export const POST_WRITE_FAILURE = "POST_WRITE_FAILURE"

// post loading
export const POST_LOADING_REQUEST = "POST_LOADING_REQUEST"
export const POST_LOADING_SUCCESS = "POST_LOADING_SUCCESS"
export const POST_LOADING_FAILURE = "POST_LOADING_FAILURE"

// post loading
export const POST_UPLOADING_REQUEST = "POST_UPLOADING_REQUEST"
export const POST_UPLOADING_SUCCESS = "POST_UPLOADING_SUCCESS"
export const POST_UPLOADING_FAILURE = "POST_UPLOADING_FAILURE"

// post detail loading
export const POST_DETAIL_UPLOADING_REQUEST = "POST_DETAIL_UPLOADING_REQUEST"
export const POST_DETAIL_UPLOADING_SUCCESS = "POST_DETAIL_UPLOADING_SUCCESS"
export const POST_DETAIL_UPLOADING_FAILURE = "POST_DETAIL_UPLOADING_FAILURE"

// post delete 
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE"